# Configuration overrides for deploying istio for testing using proxyv2 image
global:
  nodePort: true
  proxy:
    image: proxyv2

  mtls:
    enabled: false

ingress:
  enabled: true
  service:
    type: NodePort
  autoscaleMin: 1
  autoscaleMax: 8
  meshExpansion:
    enabled: false

zipkin:
  enabled: true

sidecarInjectorWebhook:
  enabled: true

prometheus:
  enabled: true
